INSERT INTO TODO_LIST (NAME) VALUES ('personal')
INSERT INTO TODO_LIST (NAME) VALUES ('groceries')
INSERT INTO TODO_LIST (NAME) VALUES ('reminders')
INSERT INTO TODO_LIST (NAME) VALUES ('shopping cart')

INSERT INTO TODO (NAME, DESCRIPTION, COMPLETED, DATE, POSITION, LIST_ID) VALUES ('Side project', 'take out the trash', false, '2022-01-01', 0, 1)
INSERT INTO TODO (NAME, DESCRIPTION, COMPLETED, DATE, POSITION, LIST_ID) VALUES ('Meditate', 'water the plants', false, '2022-01-01', 1, 1)
INSERT INTO TODO (NAME, DESCRIPTION, COMPLETED, DATE, POSITION, LIST_ID) VALUES ('Tidy desk space', 'deal with dirty laundry', false, '2022-01-01', 2, 1)
INSERT INTO TODO (NAME, DESCRIPTION, COMPLETED, DATE, POSITION, LIST_ID) VALUES ('Clean dirty dishes', 'tidy room', false, '2022-01-02', 3, 1)
INSERT INTO TODO (NAME, DESCRIPTION, COMPLETED, DATE, POSITION, LIST_ID) VALUES ('Study programming (concurrent)', 'clear table', true, '2022-02-12', 4, 1)

INSERT INTO TODO (NAME, DESCRIPTION, COMPLETED, DATE, POSITION, LIST_ID) VALUES ('egg', '', false, '2023-09-12', 1, 2)
INSERT INTO TODO (NAME, DESCRIPTION, COMPLETED, DATE, POSITION, LIST_ID) VALUES ('cereal', '', false, '2023-09-12', 2, 2)
INSERT INTO TODO (NAME, DESCRIPTION, COMPLETED, DATE, POSITION, LIST_ID) VALUES ('milk', '', false, '2023-09-12', 3, 2)