CREATE TABLE TODO_LIST (
   LIST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(255)
);

CREATE TABLE TODO (
   TODO_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(255) NOT NULL,
   DESCRIPTION VARCHAR(255),
   COMPLETED BOOLEAN,
   Date DATE,
   POSITION int,
   LIST_ID BIGINT,
   CONSTRAINT fk_todolist
      FOREIGN KEY (LIST_ID) 
      REFERENCES TODO_LIST(LIST_ID)
      ON DELETE CASCADE
);

